### ISSUE TITLE
TS1086 error with Angular 8 + TS 3.5.3

### ISSUE THREAD

**Issue by BasmaSaeed** [mselerin/ngx-security#1]
I'm using angular 8, typeScript "^3.5.3", but i have error: TS1086: An accessor cannot be declared in an ambient context. and i tried to upgrade the typescript version but the issue is not resolved

### Expected Behavior

after installing the package should work well regardless the typescript version

### Environment
 * Angular version: 8
 * ngx-security version: 2.4.0

**Comment by mselerin** [comment]
OK, I have managed to reproduce the issue.
To fix it, I had to revert back to Angular 8 for building the library.

The fixed version is published (2.4.1)
