### ISSUE TITLE
Disable Element

### ISSUE THREAD

**Issue by BasmaSaeed** [mselerin/ngx-security#2]
Is there a way/strategy to disable or enable an element (like button or input) if the user hasn't specific permission or role from the HTML file? 
I want the element to be disabled not to be hidden?

thanks in advance.

**Comment by mselerin** [comment]
The `*secuXXX` directives can only hide / show an element.

If you want to disable a button, you just have to inject the NgxSecurityService in your component and do something like that : 

```app.component.ts
@Component({
  selector: 'app-root',
  template: `
    <button [disabled]="!security.hasRole('ROLE_ADMIN')"></button>
  `
})
export class AppComponent implements OnInit {
  constructor(
    public security: NgxSecurityService
  ) {}
}
```

**Comment by BasmaSaeed** [comment]
Thank you for your response
